# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tsn',  ['core','traffic-control','network'])
    module.source = [
 		'model/TsnIpv4PacketFilter.cc',
 		'model/TsnIpv6PacketFilter.cc',
     	'helper/tsn-helper.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'tsn'
    headers.source = [
        'model/TsnIpv4PacketFilter.h',
        'model/TsnIpv6PacketFilter.h',
        'helper/tsn-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

